[package]
name = "netdump"
version = "0.2.0"
edition = "2024"

[dependencies]
cargo-watch = "8.5.2"
clap = "4.5.23"
log = "0.4.20"
pnet = "0.34.0"
rand = "0.8.5"
tokio = {version = "1", features = ["full"] }
tokio-macros = "~2.3.0"
termion = "4.0.0"
pcap = "2.2.0"

