[package]
name = "netdump"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-watch = "8.5.2"
log = "0.4.20"
pnet = "0.34.0"
rand = "0.8.5"
tokio = {version = "1", features = ["full"] }
tokio-macros = "~2.3.0"
